(ns wh.common.timezones)

(def timezones
  [["ACST" "Australian Central Standard Time" "GMT+9:30"]
   ["AEST" "Australian Eastern Standard Time" "GMT+10"]
   ["AKST" "Alaska Standard Time" "GMT-9"]
   ["AWST" "Australian Western Standard Time" "GMT+8"]
   ["BJT" "Beijing Time" "GMT+8"]
   ["BRT" "Brasilia Time" "GMT-3"]
   ["AST" "Atlantic Time Zone" "GMT-4"]
   ["BST" "British Summer Time" "GMT+1"]
   ["BST" "Bangladesh Standard Time" "GMT+6"]
   ["CAT" "Central Africa Time" "GMT+2"]
   ["CET" "Central European Time" "GMT+1"]
   ["CST" "Central Standard Time (North America)" "GMT-6"]
   ["EAT" "East Africa Time" "GMT+3"]
   ["EET" "Eastern European Time" "GMT+2"]
   ["EST" "Eastern Standard Time (North America)" "GMT-5"]
   ["GMT" "Greenwich Mean Time" "GMT+0"]
   ["GST" "Gulf Standard Time" "GMT+4"]
   ["HKT" "Hong Kong Time" "GMT+8"]
   ["HST" "Hawaii Standard Time" "GMT-10"]
   ["IST" "India Standard Time" "GMT+5:30"]
   ["IST" "Irish Summer Time" "GMT+1"]
   ["IST" "Israel Standard Time" "GMT+2"]
   ["JST" "Japan Standard Time" "GMT+9"]
   ["MET" "Middle East Time" "GMT+3:30"]
   ["MSK" "Moscow Standard Time" "GMT+3"]
   ["PETT" "Kamchatka Time" "GMT+12"]
   ["MST" "Mountain Standard Time (North America)" "GMT-7"]
   ["NZDT" "New Zealand Daylight Time" "GMT+13"]
   ["AZOT" "Azores Time" "GMT-1"]
   ["KRAT" "Krasnoyarsk Time" "GMT+7"]
   ["PST" "Pacific Standard Time (North America)" "GMT-8"]
   ["PKT" "Pakistan Standard Time" "GMT+5"]
   ["AFT" "Afghanistan Time" "GMT+4:30"]
   ["PHT" "Philippine Time" "GMT+8"]
   ["PMDT" "Pierre & Miquelon Daylight Time" "GMT-2"]
   ["NPT" "Nepal Standard Time" "GMT+5:45"]
   ["SGT" "Singapore Time" "GMT+8"]
   ["UTC" "Universal Coordinated Time" "GMT+0"]
   ["SAKT" "Sakhalin Time" "GMT+11"]
   ["SST" "Samoa Standard Time" "GMT-11"]
   ["MMT" "Myanmar Time" "GMT+6:30"]
   ["WAT" "West Africa Time" "GMT+1"]
   ["WET" "Western European Time" "GMT+0"]])
