(ns wh.terms.views)

(defn page []
  [:div.main.privacy
   [:h1 "Terms of Service"]
   [:h2 "WorksHub (A Functional Works Ltd Company) General Terms of Service"]
   [:div.container
    [:h3 "The following terms and conditions apply to all Job Seekers, Employers, Publishers and other users who access or use the Site, or otherwise indicate their acceptance to this Agreement."]
    [:ol
     [:li
      [:span.heading "The WorksHub Services"]
      [:p "WorksHub may make available certain job listings and other job-related contents, including links to third-party websites. Job Listings are created and provided by third parties over whom WorksHub exercises no control; you acknowledge and understand that we have no control over Job Listings. Except for certain sponsored, featured or paid placements.  WorksHub does not have any obligation to screen any Job Listing, or to include any Job Listing in its search results or other listings, and may exclude or remove any Job Listing from the Site for any or no reason. We cannot confirm the accuracy or completeness of any Job Listing or other information submitted by any employer or other user, including the identity of such employer or other user. WorksHub assumes no responsibility, and disclaims all liability, for the content, accuracy, completeness, legality, reliability, or availability of any Job Listing. You agree that WorksHub may also provide search options to narrow down Job Listing search results by job type (i.e. full-time, part-time, etc.), and such job types are created independently and entirely by WorksHub, and are not a direct reflection of the actual Job Listing."]
      [:p "1(a) Notice to Users Applying to Jobs Through WorksHub: If you are a Job Seeker, any resume or application information that you submit through the Site is subject to this Agreement (including Section 4 below) and to WorksHub’s Privacy Policy. Without limiting the foregoing, however, please note that by creating a public WorksHub Resume through the Site, you are requesting and authorizing WorksHub to make available your resume to any Employer that WorksHub believes may have an interest in your resume. By creating or uploading an WorksHub Resume, WorksHub may contact you to share Job Listings with you that match the contents of your WorksHub Resume. In addition, when you indicate your interest in a Job Listing through WorksHub you are requesting, you are sending your resume and application information to WorksHub, and you are requesting and authorizing WorksHub to make available such application information to the applicable Employer(s) for such Job Listing(s)"]
      [:p "1(b) If you are an Employer, when you create an WorksHub account,  or post a Job Listing on the Site, you agree that this Agreement and all of WorksHub’s policies, including the WorksHub Privacy Policy and Cookie Policy, apply to you and to the Job Seekers  indicating an interest in such Job Listings.  You also agree that, as a service to Job Seekers, WorksHub may activate its WorksHub Apply relay function for use in connection with such Job Listing, and that any Job Seekers who wish to indicate an interest in such Job Listing may only do so through WorksHub, and that WorksHub will send applications to the email address you provide us with. When you use the WorksHub notify function, you acknowledge and agree that WorksHub may add certain functions into the email, which allows you to take actions regarding the Job Seeker including, viewing a resume and rejecting a candidate, and that you consent to WorksHub monitoring and analyzing these actions. When using the WorksHub Apply function, WorksHub will attempt to send applications to the contact information provided to WorksHub by you, the Employer. WorksHub has no ability to verify the contact information provided by You. In the event You provide incorrect contact information, it shall be your responsibility to correct, appropriately respond, or take any steps necessary to protect the privacy of such Job Seekers, and you indemnify WorksHub for any damages resulting therefrom. In addition, WorksHub may, on your behalf, send out reminder emails to Job Seekers you wish to interview. WorksHub may also send emails to Job Seekers on your behalf indicating that your Job Listing is potentially a match for the Job Seeker’s resume.  WorksHub shall store such information regardless of whether a job vacancy has been filled. You are responsible for any Job Listings that you post.   You agree that WorksHub may reject or remove any Job Listing.    WorksHub may provide analytics data regarding your Employer account to anyone at your company at WorksHub’s discretion. To the extent permitted by law, if you have an unpaid or outstanding invoice or account balance for any WorksHub product, WorksHub reserves the right to suspend or terminate your use of that WorksHub product as well as any other WorksHub product, including but not limited to those WorksHub products where you do not have an unpaid invoice or account balance"]
      [:p "1(c) If you are a Job Seeker, please note that WorksHub may automatically send you recommended jobs via the email address you use to create an WorksHub account or apply to a job. WorksHub may determine what these recommended jobs are on the basis of a variety of factors, including but not limited to, any information you input on the Site about yourself, searches you run on the Site, jobs you click on, jobs you apply to, or the materials you provide in a job application to an Employer through WorksHub"]]
     [:li
      [:span.heading "External Sites"]
      [:p "The Site contains links to other sites on the Internet which are owned and/or operated by third-party vendors and other third parties (the “External Sites”). You acknowledge that WorksHub is not responsible or liable for any such third parties or for the availability of, or the materials located on or through, any External Sites. You should contact the site administrator or webmaster for the applicable External Site if you have any concerns regarding such links or the materials located on an External Site."]]

     [:li
      [:span.heading "Use of Site"]
      [:p "You are not permitted to use WorksHub’s Site or its content other than for non-commercial purposes. Use of any automated system or software, whether operated by a third party or otherwise, to extract data from the Site (such as screen scraping or crawling) is prohibited. WorksHub reserves the right to take such action as it considers necessary, including issuing legal proceedings without further notice, in relation to any unauthorized use of the Site. If you wish to make commercial use of the Site, if you wish to make use of the Site in any capacity other than that of a Jobseeker or Employer, or if you wish to purchase WorksHub services that utilize the Site, you must have a prior written agreement with WorksHub to do so, or have accepted WorksHub’s online terms of service. Please contact us for more information. We reserve the right at all times (but will not have any obligation) to terminate users, and reclaim usernames or URLs, for any reason."]]

     [:li
      [:span.heading "User Content"]
      [:p "You must not post any User Content that is unlawful, fraudulent, discriminatory, threatening, abusive, libelous, defamatory, obscene or otherwise objectionable, or that contains sexual, ethnic, racial or other discriminating slurs, or that contains no relevant or constructive content. You must also not post any User Content that contains proprietary information, trade secrets, confidential information, advertisements, solicitations, chain letters, pyramid schemes, investment opportunities, or other unsolicited commercial communication (except as otherwise expressly permitted by us in writing), or encourages or causes spamming or flooding."]
      [:p "You are prohibited from posting any User Content containing official identification information (whether your own or of another person), such as social security number, passport number, national identification number, insurance number, driver’s license number, immigration number, or any other similar number, code, or identifier. Posting such identification information may lead to identity theft and other adverse consequences. WorksHub may remove any such identification information, but does not undertake any obligation to do so, and has no responsibility and disclaims all liability for any posting of such identification information. WorksHub reserves the right to change the display of resume on its Site, including, but not limited to, hiding fields, rearranging its format, and changing visual elements."]
      [:p "Although WorksHub has no obligation to do so, WorksHub may monitor User Content, and reserves the right to delete any User Content or portion thereof that, in WorksHub’s sole discretion, violates the above rules, including any User Content that is unrelated to the specific portion of the Site on which it is posted, or that is an advertisement, recruiting or other commercial message, or that WorksHub deems in its sole discretion to be inappropriate. If you believe that any User Content violates this Agreement or our policies, please contact WorksHub immediately so that we may have the opportunity to consider its removal. For clarity, WorksHub does not have any obligation to remove any User Content, and the interpretation of whether any User Content violates any WorksHub policy will always remain within the sole discretion of WorksHub."]
      [:p "WorksHub reserves the right to disclose all User Content and other relevant information, and the circumstances surrounding their transmission, to any third party in connection with operating the Site; to protect itself, its affiliates, its partners and its visitors; and to comply with legal obligations or governmental requests. This means, for example, that WorksHub may honor subpoenas, search warrants, law enforcement or court-mandated requests to reveal a user’s electronic address and identity, or other properly requested information. As an Employer, when you post a Job Listing on WorksHub that you choose to list as confidential, your identity may be discoverable by request from the government or law enforcement"]]

     [:li
      [:span.heading "Site Rules"]
      [:p "You agree not to access (or attempt to access) the Site by any means other than through the interface that is provided by WorksHub.   You agree that you will not engage in any activity that interferes with or disrupts the Site (or the servers and networks which are connected to the Site). Unless you have been specifically permitted to do so in a separate, written agreement with WorksHub, you agree that you will not crawl, scrape, reproduce, duplicate, copy, sell, trade or resell the Site for any purpose. You agree that you are solely responsible for (and that WorksHub has no responsibility or liability to you or to any third party for) any breach of your obligations under this Agreement and for any consequences (including any loss or damage which WorksHub may suffer) of any such breach."]]

     [:li
      [:span.heading "Registration; Contact Information"]
      [:p "Some areas of the Site, including areas that may permit you to set up an WorksHub account, require you to register or provide an email address. If you so register, you agree to (a) provide true, accurate, current and complete information about yourself as prompted by our registration form (including your email address) and (b) be responsible for the confidentiality and use of your username and password, and not transfer or resell your use of or access to the Site to any third party. Please note that any individuals with whom you have shared your username and password and who are able to answer verification questions about your WorksHub account may receive access to information regarding your WorksHub account. If you are an Employer, your account is for business use and not for personal use.  WorksHub is not responsible and disclaims all liability if your email is used improperly or falsely by a third party. By registering for an WorksHub account, you agree to receive mandatory email updates regarding anomalous activity to your WorksHub account. If you attempt to send an email from a name or email address that is not true, accurate, current or complete, we reserve the right to drop such email, and attempting to send such email is a violation of our terms."]]

     [:li
      [:span.heading "Payment"]
      [:p "In connection with chargeable services, we will also collect payment information (e.g., the last four digits of credit card numbers and related verification information). All amounts payable for the Subscription Fee will be deducted automatically from the Employer credit card immediately in full. Fees paid under the Subscription Fee for Services are non-refundable, except in the case of WorksHub uncured material breach. Please note that WorksHub only has access to the last four digits of Employer credit card numbers, and does not store full credit card numbers."]
      [:p "If you are an Employer, WorksHub may request that you provide certain Personal Data to WorksHub in order to verify your account. This information may include, but may not be limited to, your Federal Employer Identification Number (EIN), Business Registration information, or a utility bill, the name and email address of an Employer representative."]
      [:p "This information will be used for internal purposes only, subject to any request by law enforcement or a court order.
All amounts payable for chargeable services are due immediately in full by credit card without deduction (unless pre-agreed)  or setoff.  Fees paid for job listings are non-refundable, except in the case of WorksHub uncured material breach."]]

     [:li
      [:span.heading "Hiring Fees"]
      [:p "For purposes of these terms of service the \"hiring fee\" shall refer to the charge for hiring a candidate whilst on any of our plans, (including both full time Employment and Contractor Engagements).  The employer agrees to pay the hiring fee charged in accordance with the fees,and billing terms agreed with WorksHub. If nothing has been pre-agreed then the Employer will pay our standard 20% hiring fee against employees first years earnings within thirty days of the employees start date."]
      [:p "In the event of a fee dispute, the employer must establish that the Employer had an active process with the Candidate before using the WorksHub Service (e.g., the Candidate had already begun the interview process with the Employer and such process had not been terminated, or the Employer had received the Candidate’s resume from an employment agency or headhunter and the). The final determination as to whether a fee is owed by the Employer will be at the sole discretion of WorksHub."]
      [:p "If you do not agree with any of the provisions of this Agreement, please terminate your account immediately.   Your obligation to pay any hiring fee will survive the termination of this agreement or the end of any subscription services."]]]]])
