(ns wh.logged-in.contribute.styles)
(def cross-posting "styles__cross-posting--2ut4Q")
(def cross-posting__publishers "styles__cross-posting__publishers--1eFIA")
(def cross-posting__publisher "styles__cross-posting__publisher--X7gx9")
(def cross-posting__a "styles__cross-posting__a--3LjZJ")
(def cross-posting__button "styles__cross-posting__button--223FF")
(def cross-posting__button--inverted "styles__cross-posting__button--inverted--3BJUj")
(def cross-posting__button--inverted-highlighted "styles__cross-posting__button--inverted-highlighted--2SHB5")
(def cross-posting__button--short "styles__cross-posting__button--short--3bdTg")
(def cross-posting__button--disabled "styles__cross-posting__button--disabled--9WjAQ")
(def cross-posting__button--dark "styles__cross-posting__button--dark--2eZzo")