(ns wh.components.newsletter.styles)
(def card "styles__card--24r-4")
(def card__wrapper "styles__card__wrapper--12zMT")
(def card__wrapper--blog-content "styles__card__wrapper--blog-content--11His")
(def card__wrapper--blog-list "styles__card__wrapper--blog-list--3vUc6")
(def card__wrapper--job-list "styles__card__wrapper--job-list--1xCWw")
(def title "styles__title--3BznZ")
(def text "styles__text--3nlQ5")
(def input "styles__input--zwvqK")
(def input__wrapper "styles__input__wrapper--DnYrm")
(def button "styles__button--i7JjI")
(def success "styles__success--l2l5T")
(def success__text "styles__success__text--1bL2-")
(def bounceInLeft "styles__bounceInLeft--uf8TJ")
(def shake "styles__shake--1CmfU")