(ns wh.components.buttons-page-navigation-styles)
(def buttons "buttons_page_navigation_styles__buttons--39jH9")
(def button "buttons_page_navigation_styles__button--eHFcV")
(def button--active "buttons_page_navigation_styles__button--active--2IWsO")
(def button__icon "buttons_page_navigation_styles__button__icon--1x4yw")
(def button--filters "buttons_page_navigation_styles__button--filters--p5aAK")
(def filters-toggle "buttons_page_navigation_styles__filters-toggle--3BLVW")