(ns wh.styles.attract-card)
(def attract-card "attract_card__attract-card--3GQdd")
(def intro "attract_card__intro--2ezbQ")
(def intro__branding "attract_card__intro__branding--CMhp_")
(def intro__icon "attract_card__intro__icon--2s5N_")
(def intro__description "attract_card__intro__description--2Snok")
(def intro__vertical-title "attract_card__intro__vertical-title--1kAhP")
(def button "attract_card__button--2rB7-")
(def contribute "attract_card__contribute--2EaEV")
(def contribute__info "attract_card__contribute__info--b6U5T")
(def contribute__heading "attract_card__contribute__heading--BwTiw")
(def contribute__copy "attract_card__contribute__copy--1uIju")
(def contribute__illustration "attract_card__contribute__illustration--1pjkK")
(def signin "attract_card__signin--1SReL")
(def signin__heading "attract_card__signin__heading--3ygBE")
(def signin__copy "attract_card__signin__copy--2UFCN")
(def signin__buttons "attract_card__signin__buttons--2G9OD")
(def cards "attract_card__cards--KoupM")