(ns wh.styles.branding)
(def vertical-title "branding__vertical-title--2537a")
(def vertical-title__line "branding__vertical-title__line--3SQLD")
(def vertical-title--multiline "branding__vertical-title--multiline--3hCyy")
(def vertical-title--navigation "branding__vertical-title--navigation--2H7Ry")
(def vertical-title--small "branding__vertical-title--small--1yFfI")
(def vertical-title--medium "branding__vertical-title--medium--p-uVo")