(ns wh.styles.buttons-page-navigation)
(def buttons "buttons_page_navigation__buttons--mZDht")
(def button "buttons_page_navigation__button--RzGnQ")
(def button--active "buttons_page_navigation__button--active--1WF_5")
(def button__icon "buttons_page_navigation__button__icon--3wTQb")