(ns wh.styles.create-job)
(def settings-card "create_job__settings-card--2i9xD")
(def settings-card__title "create_job__settings-card__title--Q6S0c")
(def checkbox "create_job__checkbox--3vGp6")
(def remuneration__checkbox "create_job__remuneration__checkbox--sOnbW")
(def remote-info "create_job__remote-info--3pzuC")
(def remote-info__section "create_job__remote-info__section--ldoSA")
(def timezone "create_job__timezone--S0QdD")
(def timezone__item "create_job__timezone__item--26Wx_")
(def timezone__close "create_job__timezone__close--Mx_ub")