(ns wh.styles.form)
(def input "form__input--38yKu")
(def input--textarea "form__input--textarea--A1gVE")
(def label__text "form__label__text--2sTct")
(def avatar "form__avatar--1BUFX")
(def avatar__wrapper "form__avatar__wrapper--1Zb03")
(def avatar__controls-wrapper "form__avatar__controls-wrapper--1x45Y")
(def avatar__controls-wrapper--disabled "form__avatar__controls-wrapper--disabled--3ZxOr")
(def avatar__edit "form__avatar__edit--1ukqS")
(def avatar__edit-icon "form__avatar__edit-icon--1-jVC")
(def error "form__error--3xs2U")