(ns wh.styles.job)
(def highlight__content "job__highlight__content--1O7Ml")
(def highlight__icon "job__highlight__icon--1zZbQ")
(def highlight__list__element "job__highlight__list__element--_psPk")
(def remote-info "job__remote-info--2reJG")