(ns wh.styles.landing)
(def page "landing__page--2REJ9")
(def page__main "landing__page__main--2aEJv")
(def side-column "landing__side-column--1krwu")
(def side-column--left "landing__side-column--left--1Ucjl")
(def main-column "landing__main-column--3d3VB")
(def card "landing__card--1Kley")
(def card--tag-picker "landing__card--tag-picker--2fgJO")
(def card--blog-published "landing__card--blog-published--1t1Ub")
(def card--job-published "landing__card--job-published--3kvVB")
(def card--matching-issues "landing__card--matching-issues--3l9_0")
(def card--company-stats "landing__card--company-stats--2p-JS")
(def card--issue-started "landing__card--issue-started--OHecJ")
(def card--matching-jobs "landing__card--matching-jobs--1xlgC")
(def loader "landing__loader--3T80b")