(ns wh.styles.modal)
(def modal "modal__modal--8bzIF")
(def modal__container "modal__modal__container--3R6Uo")
(def overlay "modal__overlay--2DaIV")
(def header "modal__header--1zAwN")
(def footer "modal__footer--101D_")
(def body "modal__body--1joac")
(def close "modal__close--28hw5")
(def close__wrapper "modal__close__wrapper--ocEVy")
(def button "modal__button--1zLKj")
(def button--secondary "modal__button--secondary--2XG9M")