(ns wh.styles.modal)
(def modal "modal__modal--D9-_D")
(def overlay "modal__overlay--3h4hC")
(def header "modal__header--2WdQK")
(def footer "modal__footer--3Wgqu")
(def body "modal__body--32sxr")
(def close "modal__close--1S-z1")
(def close__wrapper "modal__close__wrapper--3MTwN")
(def button "modal__button--2tias")
(def button--secondary "modal__button--secondary--1oBtQ")