(ns wh.styles.newsletter-subscription)
(def card "newsletter_subscription__card--1cXt6")
(def card__wrapper "newsletter_subscription__card__wrapper--3U0Pw")
(def title "newsletter_subscription__title--YbXLF")
(def text "newsletter_subscription__text--3pgUQ")
(def input "newsletter_subscription__input--2MfmU")
(def input__wrapper "newsletter_subscription__input__wrapper--3kQCi")
(def button "newsletter_subscription__button--1u9qX")
(def success "newsletter_subscription__success--1P7J9")
(def success__text "newsletter_subscription__success__text--1fGXf")
(def bounceInLeft "newsletter_subscription__bounceInLeft--36c2b")
(def shake "newsletter_subscription__shake--1AqvV")