(ns wh.styles.newsletter-subscription)
(def card "newsletter_subscription__card--2I--k")
(def card__wrapper "newsletter_subscription__card__wrapper--1rnwH")
(def card__wrapper--blog-content "newsletter_subscription__card__wrapper--blog-content--270lN")
(def card__wrapper--blog-list "newsletter_subscription__card__wrapper--blog-list--1NF9o")
(def card__wrapper--job-list "newsletter_subscription__card__wrapper--job-list--BKNnx")
(def title "newsletter_subscription__title--3hgJj")
(def text "newsletter_subscription__text--Df8E1")
(def input "newsletter_subscription__input--3OLvE")
(def input__wrapper "newsletter_subscription__input__wrapper--3BlTb")
(def button "newsletter_subscription__button--30PpR")
(def success "newsletter_subscription__success--2426t")
(def success__text "newsletter_subscription__success__text--1EKk2")
(def bounceInLeft "newsletter_subscription__bounceInLeft--n9lSm")
(def shake "newsletter_subscription__shake--eZP0R")