(ns wh.styles.payment)
(def job-quota-list "payment__job-quota-list--3xgUM")
(def job-quota-list__arrow "payment__job-quota-list__arrow--1syYr")
(def job-quota-list__content "payment__job-quota-list__content--8w-gl")
(def job-quota-list__content--open "payment__job-quota-list__content--open--2mJ48")
(def job-quota "payment__job-quota--23Zy_")
(def job-quota--checked "payment__job-quota--checked--22SRg")
(def job-quota__name "payment__job-quota__name--2soui")
(def job-quota__name__quantity "payment__job-quota__name__quantity--_bUoO")
(def package-selector__price "payment__package-selector__price--2mY5b")
(def package-selector__price--free "payment__package-selector__price--free--1LTTH")
(def package-selector__amount-per "payment__package-selector__amount-per--2SO2P")
(def package-selector__amount-billed "payment__package-selector__amount-billed--2gAne")
(def package-selector__amount "payment__package-selector__amount--3RrYP")
(def package-selector__header "payment__package-selector__header--3zccS")
(def package-selector__top-perks "payment__package-selector__top-perks--3GuQj")
(def package-selector__top-perks__item "payment__package-selector__top-perks__item--8oji1")
(def package-selector__top-perks__item__title "payment__package-selector__top-perks__item__title--1cggQ")