(ns wh.styles.register)
(def container "register__container--2NH3p")
(def card "register__card--2HlKD")
(def title "register__title--a1J1D")
(def paragraph "register__paragraph--HgjP7")
(def stackoverflow "register__stackoverflow--3hiDd")
(def auth-buttons "register__auth-buttons--1sW_P")
(def button "register__button--2sf0R")
(def input "register__input--22eSd")
(def input--error "register__input--error--2LKUT")
(def label "register__label--2UJI_")
(def label--email "register__label--email--3_eFz")
(def error "register__error--3TyVp")
(def link "register__link--1NNBp")
(def separator "register__separator--3cFaI")
(def reasons-to-apply "register__reasons-to-apply--1JnX1")
(def display-mobile "register__display-mobile--ENnwu")
(def display-not-mobile "register__display-not-mobile--2hWxD")