(ns wh.styles.side-card-mobile)
(def card "side_card_mobile__card--3KszU")
(def card__content "side_card_mobile__card__content--287o2")
(def connected-entity "side_card_mobile__connected-entity--CZL04")
(def connected-entity__title "side_card_mobile__connected-entity__title--fM3uI")
(def connected-entity__avatar "side_card_mobile__connected-entity__avatar--2savc")
(def title "side_card_mobile__title--3XeCw")
(def title--extended "side_card_mobile__title--extended--3ZpAH")
(def button "side_card_mobile__button--1B-ny")
(def horizontal-scrolling "side_card_mobile__horizontal-scrolling--QWlqm")
(def horizontal-scrolling-wrapper "side_card_mobile__horizontal-scrolling-wrapper--yq719")