(ns wh.styles.side-card-mobile)
(def card "side_card_mobile__card--ovTDb")
(def card__content "side_card_mobile__card__content--35OeO")
(def connected-entity "side_card_mobile__connected-entity--2DQg_")
(def connected-entity__title "side_card_mobile__connected-entity__title--1KVjL")
(def connected-entity__avatar "side_card_mobile__connected-entity__avatar--fxMO_")
(def title "side_card_mobile__title--31wuZ")
(def title--extended "side_card_mobile__title--extended--KvpUM")
(def button "side_card_mobile__button--25HmC")
(def horizontal-scrolling "side_card_mobile__horizontal-scrolling--14IS8")
(def horizontal-scrolling-wrapper "side_card_mobile__horizontal-scrolling-wrapper--355Z0")