(ns wh.styles.signin-buttons)
(def button "signin_buttons__button--1uldc")
(def icon "signin_buttons__icon--32o81")
(def icon--twitter "signin_buttons__icon--twitter--_mlZ7")
(def icon--email "signin_buttons__icon--email--3V0Pj")