(ns wh.styles.signin-buttons)
(def button "signin_buttons__button--1uldc")
(def icon--email "signin_buttons__icon--email--3V0Pj")
(def button--github "signin_buttons__button--github--1k7s9")
(def button--twitter "signin_buttons__button--twitter--37eoC")
(def icon--twitter "signin_buttons__icon--twitter--_mlZ7")
(def button--stackoverflow "signin_buttons__button--stackoverflow--3SX4l")
(def icon--stackoverflow "signin_buttons__icon--stackoverflow--4WQo1")
(def icon "signin_buttons__icon--32o81")