(ns wh.styles.signin-buttons)
(def button "signin_buttons__button--3ZUsn")
(def icon--email "signin_buttons__icon--email--1Jn3p")
(def button--github "signin_buttons__button--github--1vgaV")
(def button--twitter "signin_buttons__button--twitter--3kPZR")
(def icon--twitter "signin_buttons__icon--twitter--1wZKM")
(def button--stackoverflow "signin_buttons__button--stackoverflow--j7SnT")
(def icon--stackoverflow "signin_buttons__icon--stackoverflow--13rcD")
(def button--auth "signin_buttons__button--auth--2AiXL")
(def icon "signin_buttons__icon--B8QMu")