(ns wh.styles.skeletons)
(def image-with-info "skeletons__image-with-info--3CGdG")
(def image-with-info__logo "skeletons__image-with-info__logo--OidbC")
(def image-with-info__info1 "skeletons__image-with-info__info1--1sHF5")
(def image-with-info__info2 "skeletons__image-with-info__info2--3edJp")
(def paragraph "skeletons__paragraph--3qvM6")
(def paragraph__line "skeletons__paragraph__line--29cMN")
(def paragraph__line--short "skeletons__paragraph__line--short--1M50l")
(def button "skeletons__button--_-HJG")
(def title "skeletons__title--VqswM")