(ns wh.styles.skeletons)
(def image-with-info "skeletons__image-with-info--15Wo9")
(def image-with-info__logo "skeletons__image-with-info__logo--2ZtE6")
(def image-with-info__info1 "skeletons__image-with-info__info1--19OFI")
(def image-with-info__info2 "skeletons__image-with-info__info2--3IN2v")
(def paragraph "skeletons__paragraph--_kaDM")
(def paragraph__line "skeletons__paragraph__line--cgIr6")
(def paragraph__line--short "skeletons__paragraph__line--short--1caPM")
(def button "skeletons__button--1Opty")
(def title "skeletons__title--1aiYK")