(ns wh.styles.stat-card)
(def button "stat_card__button--1jae4")
(def card "stat_card__card--cgLiB")
(def text "stat_card__text--YTQlY")
(def chart "stat_card__chart--366Hi")
(def chart--percentage "stat_card__chart--percentage--1QDvk")
(def chart--icon "stat_card__chart--icon--3y6R-")