(ns wh.styles.stream-preview)
(def activity "stream_preview__activity--1G6k7")
(def date "stream_preview__date--1ukXf")
(def object-title "stream_preview__object-title--2vOMN")
(def actor "stream_preview__actor--y27xG")