(ns wh.styles.stream-preview)
(def object "stream_preview__object--ROpQ-")
(def activity "stream_preview__activity--3queF")
(def header "stream_preview__header--2xXnC")
(def show-hide "stream_preview__show-hide--2m9xc")
(def date "stream_preview__date--2ltew")
(def activity--publish "stream_preview__activity--publish--17EzA")
(def activity--highlight "stream_preview__activity--highlight--t3Evg")
(def activity--promote "stream_preview__activity--promote--nhjcr")