(ns wh.styles.tag-selector)
(def card "tag_selector__card--iBmut")
(def card--mobile "tag_selector__card--mobile--1dTAK")
(def title "tag_selector__title--1R5Ow")
(def status "tag_selector__status--2DpoL")
(def selected-counter "tag_selector__selected-counter--mw3mw")
(def reset-button "tag_selector__reset-button--3q8nM")
(def reset-button__icon "tag_selector__reset-button__icon--22CyK")