(ns wh.styles.tag-selector)
(def card "tag_selector__card--2ODKJ")
(def title "tag_selector__title--18wfY")
(def status "tag_selector__status--1ZJzO")
(def selected-counter "tag_selector__selected-counter--2j4Ie")
(def reset-button "tag_selector__reset-button--1ef8G")
(def reset-button__icon "tag_selector__reset-button__icon--2MZ55")