(ns wh.styles.tasks)
(def title "tasks__title--2pyLu")
(def subtitle "tasks__subtitle--RIsG6")
(def task "tasks__task--8_jOL")
(def task__icon "tasks__task__icon--wNzp_")
(def header "tasks__header--6sWKr")
(def tasks "tasks__tasks--3gU7z")
(def tasks__wrapper "tasks__tasks__wrapper--3Cu4L")
(def content "tasks__content--437q1")