(ns wh.styles.tasks)
(def title "tasks__title--36hqx")
(def subtitle "tasks__subtitle--2A7Kh")
(def task "tasks__task--fxmRu")
(def task__icon "tasks__task__icon--1Gqqq")
(def header "tasks__header--17IJw")
(def tasks "tasks__tasks--ReLgv")
(def tasks__wrapper "tasks__tasks__wrapper--1IJVh")
(def content "tasks__content--35Bl1")